GitHub Actions: Set the "pipefail" bash option when building docker image.
This is needed because we pipe the output of "docker build" to "ts". So if
"docker build" fails, the exit code is not the one of "ts".

diff --git a/.github/workflows/ci_build.yml b/.github/workflows/ci_build.yml
--- a/.github/workflows/ci_build.yml
+++ b/.github/workflows/ci_build.yml
@@ -23,13 +23,15 @@ jobs:
       - name: Install complementary tools
         run: sudo apt-get install -y moreutils
 
+        # We set the bash option "pipefail" to get the exit code of a failed
+        # command in a pipeline.
         # We pipe the Docker build output to ts in order to have timestamps on
         # each build step.
         # The first time stamp is a stopwatch since the invocation of
         # "docker build".
         # The second timestamp is the time taken since the previous print.
       - name: Build docker image # TODO: Maybe build docker image out of the matrix.
-        run: docker version && { docker image build -t lazuli . | ts -i "%H:%M:%S  " | ts -s "%H:%M:%S  " ; }
+        run: set -o pipefail && docker version && { docker image build -t lazuli . | ts -i "%H:%M:%S  " | ts -s "%H:%M:%S  " ; }
 
       - name: Run Lazuli container
         run: docker run -id --rm --name lazuli -v$(pwd):/~/workspace:z lazuli
